### ISSUE TITLE
상하로 긴 이미지 클릭 시 위아래 짤림

### ISSUE THREAD

**Issue by caesar-mo** [eruhoon/vega-client-svelte#27]
![image](https://user-images.githubusercontent.com/59224354/142354455-3422e584-d79b-4fe5-93dd-759d6aff26f7.png)

**Comment by eruhoon** [comment]
어케햇냐..

**Comment by caesar-mo** [comment]
![image](https://user-images.githubusercontent.com/59224354/142763887-4f8871ca-2b28-42fe-80b9-f1b02241f761.png)
그냥 이미지를 눌렀습니다.. 오른쪽의 목 긴 고양이 이미지 누른 예시 이미지 추가합니다.

**Comment by skm0416** [comment]
![before](https://user-images.githubusercontent.com/40383125/142896329-19e66c3d-802c-470c-ba36-688563474f1e.png)
![after](https://user-images.githubusercontent.com/40383125/142896335-818da092-f51c-436e-a24e-7109c7f97ea4.png)
vh를 쓰면될거같아양

**Comment by eruhoon** [comment]
1db58b0: update css for ImageViewer
