### ISSUE TITLE
붐업따 pc에서 hover시 에러

### ISSUE THREAD

**Issue by w2story** [eruhoon/vega-client-svelte#46]
이름 표기 부분 백그라운드가 처리 되지 않아 이름과 채팅이 같이 보임
(응애

**Comment by w2story** [comment]
+
표기 아이콘 이모지에서 폰트 어썸으로 변경 필

**Comment by eruhoon** [comment]
7782319c63e9db6e7e5368d0957653666c32d3e1

Conflict 우려가있으므로 Pull from origin 후 진행하십쇼

**Comment by w2story** [comment]
완료
