### ISSUE TITLE
스트리머 추가부분 아이콘 

### ISSUE THREAD

**Issue by eruhoon** [eruhoon/vega-client-svelte#49]
![image](https://user-images.githubusercontent.com/8344744/144262232-fd4335b5-765f-4fbf-bbe8-07f46e3966f4.png)

**Comment by eruhoon** [comment]
어떡하죠

**Comment by w2story** [comment]
제가 해두겠습니다.

**Comment by w2story** [comment]
![firefox_VNQ3h3kYLH](https://user-images.githubusercontent.com/39890301/144705431-5de9a60d-1862-43cb-8205-7781b0fe0ce8.png)
![firefox_H2PPoY3BgB](https://user-images.githubusercontent.com/39890301/144705444-04c89b0f-48d0-4cf4-8730-8ab07dceba76.png)
