### ISSUE TITLE
모바일 환경에서 세로로 긴 사진 업로드 할때의 문제

### ISSUE THREAD

**Issue by peng-jo** [eruhoon/vega-client-svelte#64]
예를들어 핸드폰으로 화면캡처 하고 해당 사진 업로드 하면 해당사진이 화면에 꽉차서 업로드 버튼이 보이지 않아 사진을 업로드 할 수 없습니다.

**Comment by eruhoon** [comment]
https://github.com/eruhoon/vega-client-svelte/pull/67
