### ISSUE TITLE
모바일에 볼륨 없애야함

### ISSUE THREAD

**Issue by Kandelion** [eruhoon/vega-client-svelte#66]
모바일에 방송 볼륨 컨트롤 없애야함

**Comment by eruhoon** [comment]
없애는중

**Comment by eruhoon** [comment]
![image](https://user-images.githubusercontent.com/8344744/147102627-722038ea-9f5e-439a-9c53-be89ae7f4b0f.png)

**Comment by eruhoon** [comment]
b6c30b4a6db2238cdcff6ba8eb0f4f56127330d5
